name: talaa
description: Talaa - Your ultimate travel companion app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  page_transition: ^2.1.0
  email_validator: ^3.0.0
  shimmer: ^3.0.0
  google_sign_in: '>=6.2.1 <7.0.0'   # مقفول على v6 - v7 مش متوافق مع Firebase idToken

  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.2.0
  url_launcher: ^6.2.5
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0
  aws_s3_upload_lite: ^0.1.7
  path: ^1.9.0
  dotenv: ^4.2.0

  firebase_messaging: ^16.1.3
  flutter_local_notifications: ^18.0.0

  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^7.1.0
  package_info_plus: ^9.0.1
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/hero/
    - assets/images/destinations/
    - assets/images/properties/
    - assets/images/categories/
    - assets/images/onboarding/
    - assets/images/welcome_bg.jpg
    - assets/images/login_bg.jpg
    - assets/images/register_bg.jpg
    - assets/images/icon.png
    - assets/images/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#1B4D5C"
  adaptive_icon_foreground: "assets/images/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true
