// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA-NN4mTT24sQaR6UJYShKsmsO4kXAvfc',
    appId: '1:862731638391:web:b6e8f7b21eed458f815872',
    messagingSenderId: '862731638391',
    projectId: 'login-d47c7',
    authDomain: 'login-d47c7.firebaseapp.com',
    storageBucket: 'login-d47c7.firebasestorage.app',
    measurementId: 'G-4W52S6TM79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHP1GlxDHmaaFZmrGA7aPMdKkOHgrXOCc',
    appId: '1:862731638391:android:1c748f7a7a675de1815872',
    messagingSenderId: '862731638391',
    projectId: 'login-d47c7',
    storageBucket: 'login-d47c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrKbFiVEuN0UF8g8Kgb_Ide6bFTB1aFQE',
    appId: '1:862731638391:ios:03878f579f190fd2815872',
    messagingSenderId: '862731638391',
    projectId: 'login-d47c7',
    storageBucket: 'login-d47c7.firebasestorage.app',
    androidClientId: '862731638391-3cla4s11nugdb4ac8g3qmd257h0vdrm0.apps.googleusercontent.com',
    iosClientId: '862731638391-a52fmiv08r65o68c367aogktc70u5jci.apps.googleusercontent.com',
    iosBundleId: 'com.yallatrip.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA-NN4mTT24sQaR6UJYShKsmsO4kXAvfc',
    appId: '1:862731638391:web:3f20e17a7419d899815872',
    messagingSenderId: '862731638391',
    projectId: 'login-d47c7',
    authDomain: 'login-d47c7.firebaseapp.com',
    storageBucket: 'login-d47c7.firebasestorage.app',
    measurementId: 'G-WJWCJFP515',
  );
}
