// File generated by FlutterFire CLI — fixed for Dart 3
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyM-NNWTT34sQaM6U7YShKsmsDkKXWvfc',
    appId: '1:862731638391:web:b6e8f7b21eed450f815872',
    messagingSenderId: '862731638391',
    projectId: 'login-d47c7',
    authDomain: 'login-d47c7.firebaseapp.com',
    storageBucket: 'login-d47c7.firebasestorage.app',
    measurementId: 'G-4W52S6TM79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMP1G1xDHMaaFZmrGA7aPMdKkOHgrXOCc',
    appId: '1:862731638391:android:c39a8d14ec8857f0815872',
    messagingSenderId: '862731638391',
    projectId: 'login-d47c7',
    storageBucket: 'login-d47c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyOrKbFiVEuNOUF8g0Kgb_Ide6bFTBlaFQE',
    appId: '1:862731638391:ios:971c74fdfbfbf53b815872',
    messagingSenderId: '862731638391',
    projectId: 'login-d47c7',
    storageBucket: 'login-d47c7.firebasestorage.app',
    iosBundleId: 'com.yallatrip.app.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyOrKbFiVEuNOUF8g0Kgb_Ide6bFTBlaFQE',
    appId: '1:862731638391:ios:971c74fdfbfbf53b815872',
    messagingSenderId: '862731638391',
    projectId: 'login-d47c7',
    storageBucket: 'login-d47c7.firebasestorage.app',
    iosBundleId: 'com.yallatrip.app.ios',
  );
}
